### ISSUE TITLE
Arrays 的困惑

### ISSUE THREAD

**Issue by MontyPan** [MontyPan/T-Lo#24]
額外請教：
先聲明我只是看書剛好看到有 `Arrays` 這個類別的存在，並不是偷懶偷查資料沒有自己想...
使用 `Arrays` 類別可以把原先的：

    int[] tmp = stack;
    stack = new int[length];
    for (int i = 0; i < index; i++) {
	stack[i] = tmp[i];
    }

改成：

    int[] tmp = stack;
    stack = Arrays.copyOf(tmp, length);` 

因為好奇使用 `Arrays`  類別裡面長怎樣，
所以我用 Open Declaration 功能進去看 `Arrays.copy()` ...
只有這樣：

    public static int[] copyOf(int[] original, int newLength) {
        int[] copy = new int[newLength];
        System.arraycopy(original, 0, copy, 0, Math.min(original.length, newLength));
        return copy;
    }
再進去 `System.arraycopy` 看，也只有這樣...：

    public static native void arraycopy(Object src,  int  srcPos, Object dest, int destPos, int length);

一樣只是好奇問一下，並不一定要解答：
* 像這種 預設類別 如果真的要看裡面寫了什麼東西可以去哪裡查...？
    （當然如果裡面是某種神秘難以解讀的文字，那就不用跟我說了= =+必須趕點進度Q_Q）
* 類似這種簡單、可以一下子就寫出來的功能，實務上會傾向 使用預設類別（有什麼可以用就用） 還是自己刻？
* 如果大量使用 預設類別 來解決各式各樣的問題 會造成＂可能的記憶體空間浪費＂嗎？（還要import ＸＸＸ）又或者...實務上大部分的情況不會去在乎這種事情XD？

**Comment by G100my** [comment]
咦？不會吧，又開啟副本了Q_Q！？

**Comment by MontyPan** [comment]
# 與問題無關的前言 #

這邊必須先明確的說明 / 修正一下指導原則。

以教學者的角度，當然會希望你的進度完全由我控制，最主要的原因是這樣作業才好出，比較能夠命中要害 / 促進獨立思考 blahblah。次要的理由是，我這個流派認為「自己死過才知道痛」 ~~（這個可以不用抄筆記）~~ ，自己炸過一輪才比較能夠有深切的理解。（直到前幾天你學長交的作業，我才被炸了 unchecked exception 在 API 設計上的問題.... 好痛...... :sob: ）。當然還有一個枝節末流，但說不定才是最重要的理由，就是希望你把時間花在寫作業上頭，而不是跑去看進階、甚至好高騖遠的部份，很多東西是環環相扣的（例如沒有封裝就沒有繼承、沒有繼承就沒有多型），那樣作很容易本末倒置、自以為懂了。

但是，想也知道，除非是古老年代的師徒制（徒弟還得打理師父生活起居... :scream: ），不然進度這種事情很難控制，可能光看個知識類型的 YouTube 就會吸收到一些有的沒的（喔對，我個人推薦「媽咪叔」，如果有好的頻道也歡迎推薦）。關鍵是你有沒有誠實地以自己的能力去作作業，那才是重點。

所以，你說你去追 source code 然後有一些問題，這其實很好，除了....

> # 為什麼你不開一個新的 issue 呢 #
> # 為什麼你不開一個新的 issue 呢 #
> # 為什麼你不開一個新的 issue 呢 #

你自己都說「額外請教」了，原來 issue 的 PR 已經夠亂了阿阿阿阿....... :see_no_evil: 

-------------------------------------------------------------

以下看得懂就看，看不懂就.... 有個印象就好。有些是以後會教到，有些可能永遠用不到。

當然你要繼續蓋大樓追問也沒問題，一樣歡迎，至於我會不會回答本來就是個謎團 :dancer: 

# 預設類別？WTF？ #

首先，這不是什麼「預設類別」（說好的用原文專有名詞咧？），我也不太懂為什麼你會用這個中文來形容。就字面上的意思，Java 當中只有 `java.lang.Object` 這個預設 class，用在當你宣告一個 class 而沒有指定 parent class 的時候就會以 `java.lang.Object` 作為 parent class。（這會在繼承的部份說到，看個字面上意思就好，反正只是順帶提到）

如果你的意思是 `java.lang` 這個 package 底下的 class，那也許合理，因為畢竟 `java.lang` 的 package 的確可以不用 import，但也就那樣而已。你也可以在自己的 project 裡頭搞個 `java.lang.WTF`，一點都不預設。

如果你還有更高層級的「預設 class」的說法，那我建議可以稍微去看一下 Java 9 的變革 Java Module（我承認我還沒念，都快兩年過去了...... :sob: ），開發人員可以自己決定什麼是「預設 class」（那也就沒有廣義的預設概念了）

# 像這種 預設類別 如果真的要看裡面寫了什麼東西可以去哪裡查...？ #

答：不知道，而且就算找到可能也看不懂。

關鍵點是「public static native void」（這串我們稱之為 method signature）當中的 `native`。在宣告 method 的時候用了這個關鍵字，就表示這個 method 不會以 Java 來實作，而會用 native（常見的翻譯是「原生」）的實作方式──通常是用 C 語言在各平台 / 作業系統上寫成的 dll。

這一大串東西有一個專有名詞，叫做 Java Native Interface（JNI）。我建議你知道到這裡就好，因為時至今日，有至少 99.9487% 的 Java programmer 沒有碰過 JNI 的東西（我就沒碰過 XD）。那多半是發神經想用 Java 控制硬體、或是寫到很底層得碰 OS 才會用到這招，而且你還要得會寫 C、而且還要很厲害的那種程度，不然 debug 起來是三倍的痛苦....... （對，不是雙倍，因為有可能 Java 跟 C 之間的連結設定也會出問題，還有 deploy 的問題、轉換平台的問題.... blahblah）

倒是這裡值得講一下為什麼 `System.arraycopy()`（幹他嗎的居然沒用 camel style 命名）會是 native 的，明明連你都寫得出來──ㄟ等等，這不是侮辱，我的意思是說大抵上只要會迴圈會陣列就能寫出來了，幹麼費盡千辛萬苦去搞 JNI？

答案是效率。（反正不知道原因，就猜效率就對了）

這邊會需要一些 OS、C、甚至組合語言的哏。用簡單暴力的說法（其實要講詳細我也不太行了 :speak_no_evil: ），用 native 的方式可能會直接操作記憶體、一次複製一大塊，用 Java 的方式就會真的一個 element（int）一個 element 複製，而且還要透過 JVM........

從這裡還能再講遠一點。就是這年頭（至少最近這十年），程式語言本身的效率越來越不重要了。2000 年的時候十本 Java 的書有 8.7 本會在開頭提到「Java 沒有比 C 慢多少」，現在根本沒人提了（因為更慢的語言反而還更流行 [無誤]）。甚至在系統架構上動不動就混用多個語言，然後不同語言之間用 http + JSON / XML（web api）這種慢到靠北的方式作整合（連用 socket 都懶）。

這講下去還可以扯很多，但總而言之，這年頭要用到 JNI 的機率就更渺茫了。要碰 OS 的機會基本上沒有，要控制硬體，硬體廠商可能直接給你個 web api，雙方都省事。


# 類似這種簡單、可以一下子就寫出來的功能，實務上會傾向？ #

基本上可以這樣回答：不要懷疑，有什麼用什麼。

例如像 Google 的 Guava、Apache 的 Common（這幾年可能不流行了），如果裡頭有提供，用就對了。其實這還可以一路延伸到 framework（例如 Spring）。實務上就是有什麼就用什麼，能不自己寫就不要自己寫，這樣不但省時間、出事還有機率可以推卸責任（只是有機率，大多數時候還是算在 caller 頭上 :dancer: ）。

不過呢，這還是一個典型的 trade-off。很多時候自己寫還比較快，找到「哪個 library 的哪個 class 有提供」的時間可能都已經寫完下班了，而且還不用擔心 side-effect 之類的隱憂。

請注意：寫作業是寫作業，兩個世界。更進一步說，如果你有能力寫出 library，大抵上不用擔心找不到工作。

# 大量使用 library 會造成「可能的記憶體空間浪費」嗎？ #

我把你的問題修正成這樣。

這個問題很深，你至少得理解 static、還有基本的 class loader 機制。但是我前面已經花了 2hr 寫，現在得去帶小孩了 QQ。

如果只說答案的話，對，的確有可能造成不必要的記憶體浪費。但是實務上我們不太在乎這種事情。當然如果你是設計 library / framework 的人可能要留意這方面的問題，至少不要太誇張被 caller 抓包 XD

--------

我來不及校稿了，如果錯字 or 語句不通順請挑出來詰譙，然後再原諒我 QQ
