### ISSUE TITLE
《醜奴兒》到底哪裡好？

### ISSUE THREAD

**Issue by MontyPan** [MontyPan/T-Lo#33]
# 免責聲明 #

這完全跟你找上我的原因無關（這類我會掛上「Buzz」的 label），會用 GitHub issue 純粹就只是習慣了（你要我發 PR ~~讓你享受 reject 的樂趣~~ 也行 :dancer: ），所以除了 close issue 可能需要由你來作之外，**你完全沒有義務要回應 or 花時間在上面。**

標題應該已經傳達了我的問題。所以「我的確是在不能理解的狀態下問問題試圖找答案」，在敘述我的困惑時很容易會變成是在吐嘈作品 / 作者，基本上我不會否認這樣的指控，但貶低並非我的目的、如果因此對你造成不快（畢竟是你推薦的，而且你還說「可以不斷 repeat 這張專輯」...... :hear_no_evil: ）也絕非所願，這是一個無能為力下的嘗試，我找不到其他的辦法。

------------------

在你推薦《醜奴兒》之前，我其實已經找來聽過一次（至於是去年還是前年就不記得了...），理由無他，就是他們得到了金曲獎（應該）、另外在某個 YouTuber（應該是蔡阿嘎）出題給來賓猜 or 講的時候用了「草東沒有派對」當題目，到了這種程度，想不找來聽都不行。

然後我聽了一遍，放棄 [蓋牌]。

在你的推薦清單當中又看到這個團體跟這張專輯，我有一種「該來的還是要來」的淒涼感。

過去的經驗當中，常常遇到「得重複重複再重複地聽，然後本來不怎麼樣的曲子就變得不錯」，這不限曲風，古今中外皆然，流行歌的比例是多了一點，但是古典樂卻更可怕──因為甚至得自己演奏過才會覺得不錯。當然也有怎麼聽都還是很想殺了作曲者 / 製作人的.......

扯遠了。

所以後來又至少聽了：

* Sony 藍芽喇叭 * 3（兩次聽到睡著..... XD）
* Asus 手機搭配附贈耳機 * 3（其中一次對著歌詞聽）

我不太確定《醜奴兒》的曲風是不是很吃音響器材，但橫豎我現在手邊能用的就這些了...... Orz

在這幾次的催眠下，聽是聽順耳了，但是基本上沒聽出什麼趣味，對比這張專輯得到的讚譽 or 知名程度，我實在難以理解，到底是我漏掉什麼、沒明白什麼、還是本來我就不是他們要打動的對象所以本來就無法產生共鳴？

重頭說起。

我的第一直覺有點像演歌年代的老人家聽現在的流行樂會冒出來的評語：「你們他媽的是在念經還是在唱歌？雖然你們的咬字比滷蛋周好很多，但是歌詞又是三小？」基本上即便到現在我的評語還是不會好太多，頂多潤飾成「一種結合現代實驗曲風與意識流的新詩朗誦方式，塑造出單調、沈重的壓抑氛圍，而在偶發的吶喊中才能窺見晦澀、支離破碎的歌詞背後的澎湃無力感。」個人認為，會用這種堆砌形容詞的文青風來撰寫評論，要嘛是信手拈來的大師、要嘛是想要掩蓋自己的無知的咖洨。嗯，我是後者（所以不要問我什麼是意識流）。

我的確對他們的旋律感到頭疼──如果那能稱之為旋律的話。有 87% 的歌詞是用一種喪屍般的聲調念出來，反而作為配樂的人聲（例如《勇敢的人》）還比較像主旋律。配樂也很頭疼，我很可能在第一次聽的時候就被《醜》給擊倒。《醜》那兩個吉他從頭到尾幾乎都是重複那一個或兩個小節，彷彿連安排個過門都懶（2nd 吉他表示：我就是過門），鼓聲也幾乎是毫不掩飾的只當節拍器（好啦，其實有些地方還是有些變化，很容易忽略）。由於《醜》實在醜到讓我膽怯，所以後面就放空隨他去，而每當喪屍的 vocal 出現時就又常常是那種單調的配樂，因此就給了一個印象十足的刻板印象？

所以某種角度上來說，為了寫這篇而重複重複再重複的仔細聽是有意義的。 ~~在反覆摧殘自己的耳朵之後~~ 現在當然不會用《醜》來以偏概全，不過像《爛泥》、《艾瑪》、《等》、《鬼》這幾首的配樂還是覺得十分普通，直到《山海》才對草東的配樂能力感到放心（？）。以此再進一步想：「喪屍 style 的時候配樂變得很單調」這事也十分合情合理，如果創作者的用意就是要製造出這樣的風格（而不是只能做出貧乏的配樂），那麼我所吐嘈的（那怕是《醜》）反而會是一種肯定，畢竟我的確接受到那股惡意 XD，問題就會轉變成單純個人喜好問題、以及歷史定位問題？

這個部份大概就只能到這邊了，所以改個角度，來看一下歌詞的問題。《在》實在是經典到不能再經典了：

> 她說 去你媽的花海
> 我說 妳這麼說好帥
> 她說 要把它們都打敗

在編曲上，到了這段基本上可以說是純 vocal ~~碎念~~ 清唱了，解讀成「這幾句很重要」應該不為過，那麼，這幾句到底是在說什麼呢？

不知道。

花海跟「她」有什麼過節、國仇家恨？不知道。「她」又要打敗誰？不知道（總不會是花海吧？）。上下文完全沒有提供什麼線索，我甚至開始懷疑是不是我書念太少、網紅知道太少，所以作詞者用了典故 / 哏我不知道？

當然，我不是說要什麼東西都說清楚講明白才對（那才不對），例如《大風吹》，雖然我還是不太確定到底對話的兩造是什麼身份什麼關係，但是那鄙視調侃不屑的氛圍是有的，無論是連接上面「每個人都想當鬼 都一樣的下賤」還是下面「一樣又醉了 一樣又掉眼淚」都還能解釋成表裡內外、人前人後的反差，我覺得可以說是成功。但是《在》就完全沒有解讀的可能。同樣的（但沒有那麼嚴重），《情歌》、《山海》也有一樣的問題，《我們》則是在危險邊緣。

至於其他的幾首，看文字版的話，大概就跟新詩差不多......... 但那是看文字版 :angry: 。聽歌的時候能得到多少原本歌詞文字的意思，本來就會是個問題了（嗯... 再過幾年的前端工程師就會不知道為什麼當年很喜歡唱《淚海》了， **愛以** 不能動... 還有什麼值得我心痛......）。你又搞這麼晦澀的文案、又用這麼喪屍的唱腔，那麼聽眾聽不懂以至於討厭（例如我）是不是可以被接受被原諒？一如常見只聽流行歌的人排斥古典音樂的台詞「吼... 要先聽導聆還有一堆有的沒的才能知道古典樂在幹麼，誰會有興趣阿？」

---------------

最後亡羊補牢一下，我不會說《醜奴兒》是失敗的作品，我也不敢 :speak_no_evil: ，我最多只會說那是我聽不懂、我不喜歡的風格。

話說回來，你列出來的歌單我昨天也撿了四五個來聽（例如落日飛車），蠻多就是順耳、不好也不壞、也沒留下什麼深刻印象。從這個角度來說，《醜奴兒》應該說是成功了，至少我很難忘記這張專輯。

至於《醜奴兒》的歷史定位、能不能撐過歲月的沖刷變成經典，那太難了，我跳過。

**Comment by G100my** [comment]
我也先聲明一下，我並不會感到不快，音樂這種建立在人類感官上面的東西本來就見仁見智，有的人喜歡有的人不喜歡，這完全合情合理，甚至我覺得有點有趣，畢竟我的同溫層厚到很誇張。

---------------------------------------------------------------------

延續 Hangout 所形容的表情：目瞪口呆。
你果然把他當成研究分析報告在寫了Q_Q，之前你提過想要聽聽看不一樣的音樂，所以我也很單純得列了目前台灣年輕人比較紅的音樂（除了最下面Avenged Sevenfold，那純粹是想找一個跟你反差最大的例子XD），目瞪口呆的點是 沒想到你聽音樂的角度也這麼的...在意*技術*？



> 我有一種「該來的還是要來」的淒涼感
> 所以本來就無法產生共鳴？

其實也不必這樣啦XDD  就是草東沒有 **tough** 到你的**點**而已，（原諒我用比較口語的說法）
我覺得你給我的*草東沒有派對 FeedBack* 可以牽扯到搖滾樂的精神，搖滾樂的發展也是可以用之前你分享給我的文章 - [【IT十年關鍵浪潮 5】Python：AI時代開發語言的新標準](https://www.ithome.com.tw/news/135285)那種方式去探究為什麼當時那樣的歌會受歡迎。
這方面我是沒有很去了解整個搖滾樂歷史脈絡、和後來演變出來的架構，我也是很大學時聽過社團的老師隨口提起的，最初搖滾好像是年輕人不想要一昧跟著傳統、所以用較為叛逆、激烈、引人注目、跟別人不一樣的行事生活、表達自己的想法，而**草東**所表達的大概就是 2010~2020 年這階段**台灣十幾二十幾歲大多數年輕人憂鬱的心情**啊 Q_Q（對啦我們就草莓嘛）

> 一種結合現代實驗曲風與意識流的新詩朗誦方式，塑造出單調、沈重的壓抑氛圍，而在偶發的吶喊中才能窺見晦澀、支離破碎的歌詞背後的澎湃無力感。

對啊，就是**澎湃無力感**。
說實在我聽音樂我一點都不會在意他某一首歌的某一個段落橋段過門用了什麼技巧，唱歌有沒有用什麼高難度的手段，我只會去感受聽完某一首歌，是不是與我記憶中哪一段時間、哪一段歲月、甚至哪一段曾經出現的假想，有產生共鳴、心有戚戚焉、好像感同身受的那種感覺。
之前你有提過你聽過 **老王樂隊 - 補習班門口高掛著我的照片** 不知道你的感受為何XD？ 也是只在乎整首曲子的編曲、使用哪些新的元素這樣嗎？應該不是吧。

啊提到老王，順便再來一個也是偏民謠搖滾類型的
[万能青年旅店 - 杀死那个石家庄人](https://www.youtube.com/watch?v=xbq-_2TqHVQ)
其實都是在描述某個當下的某種現象的音樂，只是草東...嗯有些真的寫得很飄渺。

> 如果創作者的用意就是要製造出這樣的風格（而不是只能做出貧乏的配樂），那麼我所吐嘈的（那怕是《醜》）反而會是一種肯定，畢竟我的確接受到那股惡意 XD，問題就會轉變成單純個人喜好問題、以及歷史定位問題？

欸...個人喜好問題就沒什麼好說的啦，歷史定位，嘿對，把全世界搖滾樂聽過一輪你就會發現這種風格還真是少有，少到我真的無從連想有哪個團的風格也是這樣「外表兩眼無神的鬱悶、內心時而無奈嘆氣、時而咧嗓嘶吼」的

> 那麼，這幾句到底是在說什麼呢？不知道。

嗯，我也不知道，意義不明就好像只是記憶裡的某個片段，我也沒有想要去了解花海怎麼了、要打敗誰呵呵。

> 但是《在》就完全沒有解讀的可能

欸呃啊？沒有啊，何必去管「她」在說什麼，反正「我」就是這樣癡癡傻傻的、重複著的迷戀著陪伴著「她」，「我」雖然期待著「她」對我說我愛你，但是那是不可能的，才沒有人會真的愛上「我」

> 愛以

IE？最近好像有看到相關文章呵呵

> 那麼聽眾聽不懂以至於討厭（例如我）是不是可以被接受被原諒？

當然啊，這東西 TMD 的主觀，完全沒有對錯，也是一堆意義不明的歌爆紅


---------------------------------------------------------------------


我的同溫層確實已經很多人把這張專輯列為心目中的經典，甚至我會覺得草東應該很難再生出一張這樣風格的專輯，這真的是主觀問題吶~~
我是覺得不用這麼嚴肅的分析這麼一張專輯啦XD
