### ISSUE TITLE
準備 GWT 開發環境

### ISSUE THREAD

**Issue by MontyPan** [MontyPan/T-Lo#38]
# 前置準備（一次性）

* 準備 maven (v3+)
* git clone https://github.com/DontCareAbout/GF
    * 完畢之後要作一次 `mvn install`
* git clone https://github.com/DontCareAbout/RQC
    1. 啟動 code server：執行 `mvn gwt:run-codeserver`，順利執行完的話會出現 `http://127.0.0.1:9876/`
    1. 開 browser 瀏覽 http://127.0.0.1:9876/
    1. 將畫面中的 `Dev Mode On` 按鈕拖曳到書籤列

--------

# 開發
* 啟動 code server（如果還沒開啟）：`mvn gwt:run-codeserver`
* 瀏覽 http://cdn.dontcareabout.us/RQC.html  （RQC 的 README.md 那個不行... 還沒時間改）
* 修改程式碼
* 回到 browser 按下 `Dev Mode On` 的書籤
    * 看到執行的結果，或是被靠腰錯誤訊息

---------

RQC 的程式進入點是 `RQCEP.start()`（package name 略）

如果你要 JS 的 alert，請用 `Window.alert("blahblah")`，如果你要 JS 的 console.log，請用 `Console.log("blahblah")`

---------

完成後請直接在 issue 回報工時， **遇到任何問題請直接 call help**

**Comment by G100my** [comment]
total: 9 hr

第一次 meeting : 45 min
開發環境安裝重新安裝撞牆期：2 hr
漫無目的閱覽 code : 1hr
第二次 meeting: 2hr
玩弄 RQC: 1hr
第三次 meeting:  2hr

另外 0.5 hr 填 韓國語字典檔，在漫無目的閱覽 code 之後
