### ISSUE TITLE
Next Meeting TODO

### ISSUE THREAD

**Issue by MontyPan** [MontyPan/T-Lo#4]
* [ ] 檢討 2019/11/15 對話
* [ ] OO 教學（如果需要）

--------

### 2019/11/15 ###
> Task-1 沒什麼問題。倒是 Task-0 我再想要不要先 merge 到 G100my，然後再直接從G100my 拉下來就好，還是直接從 MontyPan 拉下來（我必須很老實的說我因為 merge comment 不知道要寫什麼而猶豫不決哈哈哈哈哈哈

為什麼你要 merge？

> 因為 G100my 還沒有 task-1 的資料夾

這跟 task-0 有什麼關係？

> 噢~XD那我就...直接從 MontyPan 那邊拉囉

等等，我必須很認真地問，你原本想幹麼？

> 哈哈因為你不是 push 了這個 comment 那我如果之後要更新幹嘛的...先 merge 成一致不是比較方便@@?

（skip）

> 雜訊是指 ？

自己作實驗

> 好喔 （得到准許）早就超想按下去的ＸＤＤＤ
> （備註：這裡指 GitHub PR 介面的 merge pull request 按鈕）

我准許了什麼？

**Comment by G100my** [comment]
>為什麼你要 merge？

情況解釋：因為頁面上面出現那個綠色的 merge pull request，當下單細胞生物思考覺得「嗯，是不是你已經把 由我這裡送出的 pull request 接受了，所以誤以為你留的[回覆] 是你發過來的 pull request （因為綠色按鈕的關係）


[回覆]: https://github.com/MontyPan/T-Lo/pull/2#pullrequestreview-316985402


>這跟 task-0 有什麼關係？

回答：沒有關係。
情況解釋：純粹單細胞認為 當初是從 G100my 的 repo 拉下來的，所以我應該也就該從一樣的位置拉下來吧~

>等等，我必須很認真地問，你原本想幹麼？

情況解釋：當時腦子裡的步驟 接受從 Montypan → G100my的 pull request （大錯特錯），然後再從 G100my 拉到 local...

>我准許了什麼？

我....回答不出來ㄟ= =+
我回去看對話紀錄，我也**無法理解**當下**為什麼會認為你准許**了我按下那顆 merge pull request 按鈕
大概睡眠不足吧呵呵....

**Comment by MontyPan** [comment]
估計 #16 拖不了你太久 [喂]，所以要來排一下 meeting 時間。主要部份是我要教 OO 的 part-1（還有開檢討會以及開檢討會以及開檢討會）

當然，某種角度上來說，這不是必要的 meeting──如果你沒打算檢討我，而且 OO 也想自己念、純粹靠改作業的方式來補足，那的確也是可以省掉。不過我相當不建議，除了「OO 是一套思想體系」而不是單純 know-what / know-how，所以用教學的方式會比較扎實之外，也是因為日後有高達 87% 的機率我還是得講那些東西.... 而且還是用打字的方式 Orz（所以到最後可能還是要動用我的惡勢力要你 meeting XD）

我最近不行的時間是 12/20 晚上、12/21 白天可能要去看桌遊展。其餘週間的 1530～1700、2000～2400、週末的 1330～1700、2000～2400 應該都 OK。

如果你不想在 issue 上頭約時間（畢竟是公開的 repo），請開 email thread。

**Comment by G100my** [comment]
那就明天 12/20 晚上9點~~？ 如何？ : ) 

> 估計 #16 拖不了你太久

其實沒有= =+像這類型要大方向思考、分析優劣、潛在問題等，很燒腦啊...騎機車等紅燈都在想~"~

**Comment by MontyPan** [comment]
你祖母咧....

> # 我最近不行的時間是 12/20 晚上
> # 我最近不行的時間是 12/20 晚上
> # 我最近不行的時間是 12/20 晚上

你就偏偏要挑這天，請重新給個時間

**Comment by G100my** [comment]
囧  是今天（昨天的明天）啦...orz日期打錯了-_-

**Comment by MontyPan** [comment]
＝＝" 麻煩請一律打日期（雖然你前一次是打日期...... [扶額]），所以時間是 12/19 2100

> # 麻煩請你去弄個 skype #
> # 麻煩請你去弄個 skype #
> # 麻煩請你去弄個 skype #
